### ISSUE TITLE
Plan pqcp

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/libcrux#302]
This issue tracks the pqcp packaging and release policies.

**Comment by franziskuskiefer** [comment]
- APIs (pqcp feature?)
- Update script

**Comment by jschneider-bensch** [comment]
- `libcrux-ml-kem`'s `Cargo.toml` should be made independent from the workspace
- should the PQCP repo contain the necessary dependency crates (`libcrux-intrinsics`, `libcrux-sha3`, `libcrux-platform`) as well?

**Comment by jschneider-bensch** [comment]
The following `Cargo.toml` e.g. has the package metadata and release profile settings pulled down from the workspace, as well as replacing local path dependencies by the `libcrux` repo link. (This works as a first step, but in the code package there probably shouldn't be a dependency on `libcrux-dev`, right?)

```toml
[package]
name = "libcrux-ml-kem"
version = "0.0.2-pre.2"
authors = ["Cryspen"]
license = "Apache-2.0"
homepage = "https://github.com/cryspen/libcrux"
edition = "2021"
repository = "https://github.com/cryspen/libcrux"
readme = "Readme.md"
exclude = ["/tests", "/implementation_notes.pdf"]

[dependencies]
rand_core = { version = "0.6" }
libcrux-platform = { git = "https://github.com/cryspen/libcrux", version = "0.0.2-pre.2", branch = "dev" }
libcrux-sha3 = { git = "https://github.com/cryspen/libcrux", version = "0.0.2-pre.2", branch = "dev" }
libcrux-intrinsics = { git = "https://github.com/cryspen/libcrux", version = "0.0.2-pre.2", branch = "dev" }

# This is only required for verification.
# The hax config is set by the hax toolchain.
[target.'cfg(hax)'.dependencies]
hax-lib = { git = "https://github.com/hacspec/hax/" }

[features]
default = ["std"]
simd128 = ["libcrux-sha3/simd128"]
simd256 = ["libcrux-sha3/simd256"]
tests = []                         # Test utilities. DO NOT USE.
std = []

[dev-dependencies]
rand = { version = "0.8" }
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
hex = { version = "0.4.3", features = ["serde"] }
criterion = "0.5"
libcrux-ml-kem = { path = ".", features = ["tests"] }

[[bench]]
name = "ml-kem"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
```
