### ISSUE TITLE
Fix s390x build CI

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/libcrux#807]
One of the CI workflows that builds ML-KEM on s390x keeps failing unrelated to any changes we make.

I haven't looked too deeply, but it seems like an issue with the build of qemu on ubuntu that is used by the action in that workflow. (That's what I read from this comment, at least: https://github.com/docker/setup-qemu-action/issues/188#issuecomment-2613863177)

We could instead run this using some other way, perhaps, or make it non-mandatory until the upstream issues (in qemu? or ubuntu?) have been fixed.

**Comment by jschneider-bensch** [comment]
I think we can use https://github.com/docker/setup-qemu-action directly with the libcrux C build image, like [here](https://github.com/orgs/community/discussions/38728#discussioncomment-6324428).
That would allow us to [switch qemu to a working version](https://github.com/docker/setup-qemu-action/issues/188#issuecomment-2604322104):
```
      uses: docker/setup-qemu-action@v3.3.0
      with:
        image: tonistiigi/binfmt:qemu-v8.1.5
        platforms: ${{ inputs.platforms }}
```
